name: "Terraform with LocalStack"

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:0.14.1
        ports:
          - 4566:4566
        env:
          SERVICES: ec2,iam,vpc
          AWS_DEFAULT_REGION: us-east-1
        options: >-
          --health-cmd="curl -s http://localhost:4566/health || exit 1"
          --health-interval=3s
          --health-timeout=2s
          --health-retries=15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Terraform phiên bản ổn định nhất
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.3.7"

    # Đợi LocalStack (siêu nhanh)
    - name: Wait LocalStack Ready
      run: |
        echo "Waiting for LocalStack..."
        for i in {1..10}; do
          nc -z localhost 4566 && echo "LocalStack up!" && break
          echo "Not ready, retry in 3s..."
          sleep 3
        done

    - name: Terraform Format
      run: terraform -chdir=terraform fmt -recursive

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Plan
      run: terraform -chdir=terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform -chdir=terraform apply -auto-approve -input=false
